app/models/ability_model.py
import re
class Ability:
    '''Blueprint to create abilities'''    
    
    ABILITY_LEVELS = {
        'perk1' : 1,
        'perk2' : 2,
        'perk3' : 3,
        'flaw1' : -1,
        'flaw2' : -2,
        'flaw3' : -3,
    }
    
    ALT_STATS = {
    "strike": "sorcery",
    "sorcery": "strike",
    "armor": "warding",
    "warding": "armor"        
    }
            
    def __init__(self, name: str, description: str, level: str):
        
        if not name:
            raise ValueError("Namme cannont be empty")
        if not description:
            raise ValueError("Description cannont be empty")
        if level not in Ability.ABILITY_LEVELS:
            raise ValueError(f"Invalid level: {level}")
        self._name = name
        self._description = description
        self._level = level
        self.alt_name = ""
        self.alt_description= description
        self.create_alt_version()      
                
    @property
    def name(self):
        '''Name getter'''
        return self._name
    
    @name.setter
    def name(self, new_name: str):
        '''Name setter'''
        if not new_name:
            raise ValueError("Name cannot be empty")
        self._name = new_name
        
    @property
    def description(self):
        '''Description getter'''
        return self._description
    
    @description.setter
    def description(self, new_description: str):
        '''Description setter'''
        if not new_description:
            raise ValueError("Description cannont be empty")
        self._description = new_description
        
    def create_alt_version(self):
            '''Creates an alternate ability if possible'''
            self.alt_description = re.sub(r'\b' + '|'.join(re.escape(key) for key in self.ALT_STATS.keys()) + r'\b', lambda m: self.ALT_STATS[m.group(0)], self.alt_description)
            self.alt_name = "Magical " + self._name

app/routes/ability_create.py
from flask import Flask, render_template, flash, request, Blueprint, url_for, redirect
from app.models.ability_model import Ability
from main import get_database_connection

create_ability_blueprint = Blueprint('create_ability', __name__)

@create_ability_blueprint.route('/ability/create', methods=['GET', 'POST'])
def create_ability():
    if request.method == 'POST':
        name = request.form['name']
        description = request.form['description']
        level = request.form['level']
        
        try:
            ability = Ability(name, description, level)
            conn = get_database_connection()
            cursor = conn.cursor()
            cursor.execute('INSERT INTO abilities (name, description, level) VALUES (?,?,?)', (name, description, level))
            conn.commit()
            if ability.alt_description != ability.description:
                conn = get_database_connection()
                cursor = conn.cursor()
                cursor.execute('INSERT INTO abilities (name, description, level) VALUES (?,?,?)', (ability.alt_name, ability.alt_description, level))
                conn.commit()
                flash('Alt ability created', 'success')
            flash('Ability created.', 'success')     
            return redirect(url_for('index.home'))
        except ValueError as error:
            flash(str(error))
            
    levels = Ability.ABILITY_LEVELS
    return render_template('add_ability.html', levels = levels)          

app/routes/ability_index.py
from flask import Flask, render_template, request
from main import get_database_connection



def get_all_abilities():
    conn = get_database_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * from abilities')
    abilities = cursor.fetchall()
    return abilities

app/routes/ability_show.py
from flask import Flask, render_template, request, Blueprint, abort
from main import get_database_connection

show_ability_blueprint = Blueprint('show_ability', __name__)

@show_ability_blueprint.route('/ability/<ability_name>')
def ability_show(ability_name):
    conn = get_database_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM abilities WHERE name = ?', (ability_name,))
    ability = cursor.fetchone()
    
    if ability is None:
        abort(404)
        
    return render_template('ability_detail.html', ability=ability)

app/routes/edit_card.py
from flask import Flask, render_template, request, redirect, url_for, Blueprint, flash
from main import get_database_connection

edit_cards_blueprint = Blueprint('edit_card', __name__)

@edit_cards_blueprint.route('/edit/<card_name>', methods=['GET'])
def show_edit_card_form(card_name):
    conn = get_database_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM cards WHERE name = ?', (card_name,))
    card = cursor.fetchone()
    if card is None:
        flash('Card not found.', 'error')
        return redirect(url_for('index'))
    return render_template('edit_card.html', card=card)

@edit_cards_blueprint.route('/edit/<card_name>', methods=['POST'])
def edit_card_name(card_name):
    new_name = request.form['card_name']
    conn = get_database_connection()
    cursor = conn.cursor()
    cursor.execute('UPDATE cards SET name = ? WHERE name = ?', (new_name, card_name))
    conn.commit()
    flash('Card name updated successfully.', 'success')
    return redirect(url_for('show_card.card_show', card_name=new_name))

app/routes/index.py
from flask import Flask, render_template, request, Blueprint
from main import get_database_connection
from app.routes.ability_index import get_all_abilities


index_blueprint = Blueprint('index', __name__)


@index_blueprint.route('/')
def home():
    abilities = get_all_abilities()
    page = request.args.get('page', 1, type=int)    
    offset = (page - 1) * 12
    conn = get_database_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * from cards LIMIT 12 OFFSET ?', (offset, ))
    data = cursor.fetchall()
    return render_template('card_list.html', data = data, current_page=page, abilities=abilities)

app/routes/show.py
from flask import Flask, render_template, request, Blueprint, abort
from main import get_database_connection

show_card_blueprint = Blueprint('show_card', __name__)

@show_card_blueprint.route('/card/<card_name>')
def card_show(card_name):
    conn = get_database_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM cards WHERE name = ?', (card_name,))
    card = cursor.fetchone()
    
    if card is None:
        abort(404)
        
    return render_template('card_detail.html', card=card)

main.py
from flask import Flask
import sqlite3


def get_database_connection():
    conn = sqlite3.connect('database.db')
    conn.row_factory = sqlite3.Row
    return conn

def create_app():
    app = Flask(__name__)
    app.secret_key = 'doomer69'
    

    from app.routes.index import index_blueprint
    from app.routes.show import show_card_blueprint
    from app.routes.edit_card import edit_cards_blueprint
    from app.routes.ability_show import show_ability_blueprint
    from app.routes.ability_create import create_ability_blueprint
    
    
    app.register_blueprint(index_blueprint)
    app.register_blueprint(show_card_blueprint)
    app.register_blueprint(edit_cards_blueprint, url_prefix='/card')
    app.register_blueprint(show_ability_blueprint)
    app.register_blueprint(create_ability_blueprint)

    
    return app

templates/abilities_dropdown.html
<div class="navbar-item has-dropdown is-hoverable">
    <a class="navbar-link">
        Abilities
    </a>
    <div class="navbar-dropdown">
        {% for ability in abilities %}
            <a href="{{ url_for('show_ability.ability_show', ability_name=ability.name)}}" class="navbar-item">
                {{ ability.name }}
            </a>
            {% endfor %}
        </div>
</div>

templates/ability_detail.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ability.name}}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {{ability.name}}
        <a href="{{ url_for('index.home')}}">Index</a>
    </body>
</html>

templates/add_ability.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Add Ability</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />
  </head>
  <body>
    <section class="section">
      <div class="container">
        <form
          method="post"
          action="{{ url_for('create_ability.create_ability') }}"
        >
          <div class="field">
            <label class="label" for="name">Ability Name</label>
            <div class="control">
              <input
                class="input"
                type="text"
                name="name"
                placeholder="Ability Name"
                required
              />
            </div>
          </div>

          <div class="field">
            <label class="label" for="description">Description</label>
            <div class="control">
              <textarea
                class="textarea"
                name="description"
                placeholder="Description"
                required
              ></textarea>
            </div>
          </div>

          <div class="field">
            <label class="label" for="level">Level</label>
            <div class="control">
              <div class="select">
                <select name="level">
                  {% for level_name, level_value in levels.items() %}
                  <option value="{{ level_name }}">{{ level_name }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <button type="submit" class="button is-primary">
                Create Ability
              </button>
            </div>
          </div>
        </form>
        <a class="button is-light" href="{{ url_for('index.home')}}">Back</a>
      </div>
    </section>
  </body>
</html>

templates/card_detail.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{card.name}}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    </head>
    <body>     

    <section class="section">
      <div class="container">
      <div class="columns is-multiline">
        <div class="column is-one-quarter">
          <div class="box">Strike </br> {{ card.strike }}</div>          
        </div>
        <div class ="column">
          <div class="box">Name </br> {{ card.name }}</div>          
        </div>
        <div class="column is-one-quarter">
          <div class="box">Armor </br> {{ card.armor }}</div>          
        </div>
      </div>
      <div class="columns is-multiline">
        <div class="column is-one-quarter">
          <div class="box">Sorcery </br> {{ card.sorcery }}</div>          
        </div>
        <div class="column">
          <div class="box">Rank </br> {{ card.rank }}</div>          
        </div>
        <div class="column is-one-quarter">
          <div class="box">Warding </br> {{ card.warding }}</div>          
        </div>
      </div>
      <div class="columns is-multiline">
        <div class="column">
          <div class="box">Abilities </br>
            <ul>
              {% set abilities_list = card.abilities.strip('[]"').split(',') %}
              {% for ability in abilities_list %}
                  <li><a href="{{ url_for('show_ability.ability_show', ability_name=ability.strip().strip('"')) }}">{{ ability.strip().strip('"') }}</a></li>
              {% endfor %}
          </ul>
          </div>          
        </div>
      </div>
      <div class="columns is-multiline">
        <div class="column">
          <div class="box">Rarity </br> {{ card.rarity }}</div>          
        </div>        
      </div>
      <div class="columns is-multiline">
        <div class="column is-one-third">
          <div class="box">Movement </br> {{ card.movement }}</div>          
        </div>
        <div class="column is-one-third">
          <div class="box">HP </br> {{ card.hp }}</div>          
        </div>
        <div class="column is-one-third">
          <div class="box">Range </br> {{ card.ranged }}</div>          
        </div>
      </div>
      </div>
    </div>
    <div class="buttons">
      <a class="button is-info" href="{{ url_for('edit_card.show_edit_card_form', card_name=card.name) }}">Edit Name</a>
      <a class="button is-light" href="{{ url_for('index.home')}}">Index</a>
  </div>
    </section>
    </body>
</html>

templates/card_list.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Warfinder</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  </head>
  <body>
    {% include 'abilities_dropdown.html' %}
    <section class="section">
      <div class="container">
          <!-- Card List -->
          <div class="columns is-multiline">
              {% for card in data %}
                  <div class="column is-one-quarter">
                      <div class="card">
                          <header class="card-header">
                              <p class="card-header-title">
                                  {{ card.name }}
                              </p>
                          </header>
                          <div class="card-content">
                              <div class="content">
                                  {{ card.rank }}
                                  <br>
                                  <a href="{{ url_for('show_card.card_show', card_name = card.name) }}">Learn more</a>
                              </div>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>




    <nav class="pagination" rolle="navigation" aria-label="pagination">


    <a href="{{ url_for('index.home', page=current_page-1) }}" class="pagination-previous">Previous</a> 
    <a href="{{ url_for('index.home', page=current_page+1)}}" class="pagination-next">Next</a>

    </nav>
    <div class="has-text-centered">
      <a href={{ url_for('create_ability.create_ability')}} class="button">Add Ability</a>

    </div>


  </body>
</html>

templates/edit_card.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Edit {{card.name}}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Edit Card Name</h1>
        <form method="post" action="{{ url_for('edit_card.edit_card_name', card_name=card.name )}}">
           <label for="card_name">New Name:</label>
           <input type="text" name="card_name" value="{{ card.name }}" required>
           <input type="submit" value="Update Name">
        </form>
        
        
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Warfinder</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  </head>
  <body>
    <section class="section">
      <div class="container">
          <!-- Card List -->
          <div class="columns is-multiline">
              {% for card in data %}
                  <div class="column is-one-quarter">
                      <div class="card">
                          <header class="card-header">
                              <p class="card-header-title">
                                  {{ card.name }}
                              </p>
                          </header>
                          <div class="card-content">
                              <div class="content">
                                  {{ card.rank }}
                                  <br>
                                  <a href="{{ url_for('show_card.card_show', card_name = card.name) }}">Learn more</a>
                              </div>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>




    <nav class="pagination" rolle="navigation" aria-label="pagination">


    <a href="{{ url_for('index.home', page=current_page-1) }}" class="pagination-previous">Previous</a> 
    <a href="{{ url_for('index.home', page=current_page+1)}}" class="pagination-next">Next</a>

    </nav>
    <div class="has-text-centered">
      <a href={{ url_for('create_ability.create_ability')}}>Add Ability</a>

    </div>


  </body>
</html>